export const HYDRATE_STATE = 'HYDRATE_STATE';

// ORGANIZATIONS
export const ORGANIZATION_FETCH_LIST = "ORGANIZATION_FETCH_LIST";
export const ORGANIZATION_FETCH_LIST_FULFILLED = "ORGANIZATION_FETCH_LIST_FULFILLED";
export const ORGANIZATION_FETCH_LIST_REJECTED = "ORGANIZATION_FETCH_LIST_REJECTED";
export const ORGANIZATION_FETCH_LIST_PENDING = "ORGANIZATION_FETCH_LIST_PENDING";
export const ORGANIZATION_FETCH = "ORGANIZATION_FETCH";
export const ORGANIZATION_FETCH_FULFILLED = "ORGANIZATION_FETCH_FULFILLED";
export const ORGANIZATION_FETCH_REJECTED = "ORGANIZATION_FETCH_REJECTED";
export const ORGANIZATION_FETCH_PENDING = "ORGANIZATION_FETCH_PENDING";

//EVENTS
export const EVENT_FETCH_LATEST = "EVENT_FETCH_LATEST";
export const EVENT_FETCH_LATEST_PENDING = "EVENT_FETCH_LATEST_PENDING";
export const EVENT_FETCH_LATEST_REJECTED = "EVENT_FETCH_LATEST_REJECTED";
export const EVENT_FETCH_LATEST_FULFILLED = "EVENT_FETCH_LATEST_FULFILLED";
// CASES
export const CASE_FETCH_LATEST = "CASE_FETCH_LATEST";
export const CASE_FETCH_LATEST_PENDING = "CASE_FETCH_LATEST_PENDING";
export const CASE_FETCH_LATEST_REJECTED = "CASE_FETCH_LATEST_REJECTED";
export const CASE_FETCH_LATEST_FULFILLED = "CASE_FETCH_LATEST_FULFILLED";